#include "./gdt.h"

void GDTSetGeneralSegments()
{
    GDTSetEntry(
        GDT_ENTRY_NULL, 
        0x0000, 
        0x0000, 
        0x0000, 
        0x0000 );

    GDTSetEntry(
        GDT_ENTRY_KERNEL_CODE, 
        0xFFFF, 
        0x0000,
        GDT_ACCESS_PRESENT | GDT_ACCESS_RING0 | GDT_ACCESS_CODE_SEGMENT | GDT_ACCESS_CODE_READABLE,
        GDT_FLAG_32BIT | GDT_FLAG_GRANULARITY_4K );

    GDTSetEntry(
        GDT_ENTRY_KERNEL_DATA,
        0xFFFF,
        0x0000,
        GDT_ACCESS_PRESENT | GDT_ACCESS_RING0 | GDT_ACCESS_DATA_SEGMENT | GDT_ACCESS_DATA_WRITEABLE,
        GDT_FLAG_32BIT | GDT_FLAG_GRANULARITY_4K );
    
    GDTSetEntry(
        GDT_ENTRY_USER_CODE,
        0xFFFF,
        0x0000,
        GDT_ACCESS_PRESENT | GDT_ACCESS_RING3 | GDT_ACCESS_CODE_SEGMENT | GDT_ACCESS_CODE_READABLE,
        GDT_FLAG_32BIT | GDT_FLAG_GRANULARITY_4K );

    GDTSetEntry(
        GDT_ENTRY_USER_DATA,
        0xFFFF,
        0x0000,
        GDT_ACCESS_PRESENT | GDT_ACCESS_RING3 | GDT_ACCESS_DATA_SEGMENT | GDT_ACCESS_DATA_WRITEABLE,
        GDT_FLAG_32BIT | GDT_FLAG_GRANULARITY_4K );
}